### PR TITLE
Added issue templates

### PR DESCRIPTION
**Pull request by lextm**
New users might miss very important information when opening their first issues, so adding such templates can help them out.

### CODE REVIEW

**Comment by alcarney** [comment]
Thanks for this!

However, I don't want to add too much ceremony too quickly. I'd rather start simple and build the templates up as the need arises. Could we start with just the bug report template and have it ask just for the expected/actual behavior and the log output?

Version numbers and all the other info can easily be included in the logs.

**Comment by lextm** [comment]
> Version numbers and all the other info can easily be included in the logs.

Then maybe use another pull request to make sure all necessary version numbers are printed to the logs. Currently I can only see sphinx version printed out, no OS nor Python version.

**Comment by alcarney** [comment]
> Then maybe use another pull request to make sure all necessary version numbers are printed to the logs.

Sure that sounds great :)

**Comment by alcarney** [comment]
As of https://github.com/swyddfa/esbonio/commit/ebef91eb5e98e64b64732724e70ff3781aa80df0 the server will now log Python version and OS

**Comment by alcarney** [comment]
Thanks!

**Pull request merged**
