### PR TITLE
Migrate to pygls v1.0

### LINKED ISSUE #400: Dropping Python 3.6
Pygls will be [dropping Python 3.6](https://github.com/openlawlibrary/pygls/issues/235) support soon so we will have to do the same.
I'm planning to hold on though until Sphinx drops 3.6 support in Sphinx 6.x.

In general, it's probably worth supporting whatever Sphinx supports for some sensible range of Sphinx versions. - See #401

### PR DESCRIPTION
**Pull request by alcarney**
~*This is very early and very rough but I think it's worth giving people the heads up that this is coming.*~

`pygls`, the library that `esbonio` relies on for it's language server protocol implementation has released v1.0 with some breaking changes (see openlawlibrary/pygls#273 more details), this PR migrates `esbonio` to this new version.
These changes may or may not affect you, depending on how you use `esbonio`.

**End Users**

Apart from dropping Python v3.6 support, there should be no breaking changes in `esbonio`

**Integrators**

As mentioned above Python v3.6 will no longer be supported, and some transitive dependencies will change but everything else (config values, notifications etc) should remain the same.

**Extension Authors**

There unfortunately, will be breaking changes but they will be due to implementation details from `pygls` leaking through rather than any changes to esbonio's APIs. Hopefully this means the migration is not too painful.

A migration guide for pygls is still being worked on, but here's some of the highlights.
- The `pygls.lsp.types` and `pygls.lsp.methods` modules have been removed, all LSP type and method definitions are now provided by the [lsprotocol](https://github.com/microsoft/lsprotocol) package
-  LSP type and method definitions are no longer defined using `pydantic`, but with `attrs` and using `cattrs` for serialization/deserialization

~While~ testing will certainly be appreciated, ~I don't think this PR is quite ready for that as I am already aware of some issues that require further changes upstream in `pygls`. I am also not expecting this to land for a while yet and intend to make at least one more release based on the old version of `pygls`.~

*Pinging some people who probably have an interest in this*
@lextm @yaegassy @danwos @haiyangToAI 

Let me know if you have any thoughts

Closes #400

### CODE REVIEW

**Comment by alcarney** [comment]
pygls v1.0 is now out and the migration is done, I just need to get an updated version of `pytest-lsp` out so that the test suite passes in CI.

I'd say this was ready to test if anyone fancies trying this branch out. There is also [a migration guide](https://pygls.readthedocs.io/en/latest/pages/migrating-to-v1.html) for pygls which you might find useful if you're an extension author.

The plan is to include this in the next feature release `v0.16.0`

**Comment by polyzen** [comment]
Happy holidays! Any ETA on this? Latest jedi-language-server and the new ruff-lsp require pygls 1.0.0. Esbonio and jedi-ls are available for system installation in the Arch repos, and I would like to make a ruff-lsp package for the AUR.

**Comment by alcarney** [comment]
Happy holidays to you too! :smile: 
ETA I expect will be sometime in January (hopefully sooner rather than later).

Technically the only thing holding this up is a new release of [`pytest-lsp`](https://github.com/alcarney/lsp-devtools/tree/develop/lib/pytest-lsp) which will unblock CI. 

That said, I'd also like to get #514 merged first as I'd rather not force the migration onto @stsewd if I can help it, but we'll see how it goes.

**Comment by polyzen** [comment]
Works for me, backported this PR in the meantime:
https://github.com/archlinux/svntogit-community/commit/38bb6aa7e433c3a3b5c710d7646d4acb7d7ae15d

**Pull request merged**
