### PR TITLE
WIP: Fix #790: preview server - Uses Thread instead of Process for Linux

### LINKED ISSUE #790: Preview of rst files not working
### Expected behavior

When starting a preview window, I expect a new window to appear after Sphinx successfully builds the project.

### Actual behavior

Sphinx completes the build, but when issuing `esbonio.preview`, the server connection errors and times out. I am using the stable version of the esbonio VSCode extension 0.11.0 as the preview does not work, and I cannot cause it to log. I am on a MacBook Pro M1 (2021) with OSX Ventura 13.5.2. Note that I have no issues with the same stack when using my Windows 11 desktop.

### Log output

```shell
[client] Python extension is available
[client] Activating python extension
[client] Running Command: /Users/will/miniforge3/envs/pyscope-dev/bin/python -c import sys ; print("{0.major}.{0.minor}.{0.micro}".format(sys.version_info))
[client] Python version: '3.12.3'
[client] Running Command: /Users/will/miniforge3/envs/pyscope-dev/bin/python -m esbonio --version
[client] Server version '0.16.4'
[client] Server version '0.16.4'
[client] Last update was 2024-04-24T17:12:19.225Z
[client] Server start command: /Users/will/miniforge3/envs/pyscope-dev/bin/python -m esbonio
[client] LanguageClientOptions: {
  "documentSelector": [
    {
      "scheme": "file",
      "language": "restructuredtext"
    },
    {
      "scheme": "file",
      "language": "python"
    }
  ],
  "initializationOptions": {
    "sphinx": {
      "buildDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/_build",
      "builderName": "html",
      "confDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source",
      "configOverrides": {},
      "doctreeDir": null,
      "forceFullBuild": false,
      "keepGoing": false,
      "makeMode": true,
      "numJobs": 1,
      "quiet": false,
      "silent": false,
      "srcDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source",
      "tags": [],
      "verbosity": 0,
      "warningIsError": false
    },
    "server": {
      "logLevel": "debug",
      "logFilter": [],
      "hideSphinxOutput": false,
      "showDeprecationWarnings": false,
      "completion": {
        "preferredInsertBehavior": "replace"
      }
    }
  },
  "outputChannel": {
    "name": "Esbonio"
  }
}
[client] Starting Language Server
[esbonio.lsp] Loaded extension 'esbonio.lsp.directives'
[esbonio.lsp] Loaded extension 'esbonio.lsp.roles'
[esbonio.lsp] Loaded extension 'esbonio.lsp.rst.directives'
[esbonio.lsp] Loaded extension 'esbonio.lsp.rst.roles'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.autodoc'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.codeblocks'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.domains'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.directives'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.images'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.includes'
[esbonio.lsp] Loaded extension 'esbonio.lsp.sphinx.roles'
[esbonio.lsp] User Config {
  "buildDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/_build",
  "confDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source",
  "srcDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source"
}
[esbonio.lsp] Workspace Folder: 'file:///Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope'
[esbonio.lsp] Sphinx Args {
  "buildername": "html",
  "confdir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source",
  "confoverrides": {},
  "doctreedir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/_build/doctrees",
  "freshenv": false,
  "keep_going": false,
  "outdir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/_build/html",
  "parallel": 1,
  "srcdir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source",
  "status": null,
  "tags": [],
  "verbosity": 0,
  "warning": null,
  "warningiserror": false
}
Running Sphinx v7.2.6
[esbonio.lsp] Reporting diagnostic at file:///Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/conf.py:1
WARNING: directive 'autoattribute' is already registered, it will be overridden
[esbonio.lsp] Reporting diagnostic at file:///Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/conf.py:1
WARNING: directive 'testsetup' is already registered, it will be overridden
[esbonio.lsp] Reporting diagnostic at file:///Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/conf.py:1
WARNING: directive 'testcleanup' is already registered, it will be overridden
[esbonio.lsp] Reporting diagnostic at file:///Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/conf.py:1
WARNING: directive 'doctest' is already registered, it will be overridden
loading pickled environment...
done
loading intersphinx inventory from /Users/will/miniforge3/envs/pyscope-dev/lib/python3.12/site-packages/sphinx_astropy/local/python3_local_links.inv...
[autosummary] generating autosummary for: api/auto_api/pyscope.analysis.calc_zmag.rst, api/auto_api/pyscope.observatory.ASCOMCamera.rst, api/auto_api/pyscope.observatory.ASCOMCoverCalibrator.rst, api/auto_api/pyscope.observatory.ASCOMDevice.rst, api/auto_api/pyscope.observatory.ASCOMDome.rst, api/auto_api/pyscope.observatory.ASCOMFilterWheel.rst, api/auto_api/pyscope.observatory.ASCOMFocuser.rst, api/auto_api/pyscope.observatory.ASCOMObservingConditions.rst, api/auto_api/pyscope.observatory.ASCOMRotator.rst, api/auto_api/pyscope.observatory.ASCOMSwitch.rst, ..., development/workflow.rst, index.rst, installation.rst, license.rst, user_guide/config.rst, user_guide/examples.rst, user_guide/header.rst, user_guide/help.rst, user_guide/index.rst, user_guide/logging.rst
[automodsumm] api/pyscope.observatory.rst: found 35 automodsumm entries to generate
[automodsumm] api/pyscope.utils.rst: found 3 automodsumm entries to generate
[automodsumm] api/pyscope.reduction.rst: found 5 automodsumm entries to generate
[automodsumm] api/pyscope.telrun.rst: found 14 automodsumm entries to generate
[automodsumm] api/pyscope.analysis.rst: found 1 automodsumm entries to generate
The default value for `navigation_with_keys` will change to `False` in the next release. If you wish to preserve the old behavior for your site, set `navigation_with_keys=True` in the `html_theme_options` dict in your `conf.py` file. Be aware that `navigation_with_keys = True` has negative accessibility implications: https://github.com/pydata/pydata-sphinx-theme/issues/1492
[esbonio.lsp] Skipping extension 'sphinx.addnodes', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.changes', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.epub3', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.mathjax', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.html.transforms', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.html', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.dirhtml', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.dummy', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.gettext', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.latex.transforms', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.latex', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.linkcheck', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.manpage', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.singlehtml', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.texinfo', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.text', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.builders.xml', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.config', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.c', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.changeset', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.citation', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.cpp', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.index', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.javascript', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.math', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.directives', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.python', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.rst', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.domains.std', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.directives.code', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.directives.other', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.directives.patches', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.extension', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.parsers', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.registry', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.roles', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.transforms', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.transforms.compact_bullet_list', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.transforms.i18n', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.transforms.references', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.transforms.post_transforms', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.transforms.post_transforms.code', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.transforms.post_transforms.images', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.versioning', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.environment.collectors.dependencies', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.environment.collectors.asset', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.environment.collectors.metadata', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.environment.collectors.title', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.environment.collectors.toctree', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'alabaster', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinxcontrib.applehelp', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinxcontrib.devhelp', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinxcontrib.htmlhelp', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinxcontrib.serializinghtml', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinxcontrib.qthelp', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.autodoc.preserve_defaults', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.autodoc.type_comment', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.autodoc.typehints', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.autodoc', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.coverage', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.graphviz', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.inheritance_diagram', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.intersphinx', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.todo', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.linkcode', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinxcontrib.jquery', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.autosummary', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'numpydoc', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_copybutton', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'pytest_doctestplus.sphinx.doctestplus', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_astropy.ext.changelog_links', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_astropy.ext.generate_config', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_astropy.ext.intersphinx_toggle', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_astropy.ext.missing_static', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_automodapi.autodoc_enhancements', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_automodapi.automodsumm', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_automodapi.automodapi', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_automodapi.smart_resolver', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'matplotlib.sphinxext.plot_directive', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx_favicon', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'sphinx.ext.doctest', missing 'esbonio_setup' fuction
[esbonio.lsp] Skipping extension 'pydata_sphinx_theme', missing 'esbonio_setup' fuction
[esbonio.lsp] Building...
[client] Build start.
building [mo]: targets for 0 po files that are out of date
writing output...

building [html]: targets for 0 source files that are out of date
updating environment:
0 added, 1 changed, 0 removed
[2K
reading sources... [100%]
user_guide/header


looking for now-outdated files...
none found
pickling environment...
done
checking consistency...
done
preparing documents...
done
copying assets...
copying static files...
done
copying extra files...
done
done
[2K
writing output... [ 33%]
index

[2K
writing output... [ 67%]
user_guide/header

[2K
writing output... [100%]
user_guide/index


generating indices...
genindex
py-modindex
done
writing additional pages...
search
done
dumping search index in English (code: en)...
done
dumping object inventory...
done
build succeeded.

The HTML pages are in docs/source/_build/html.
[client] Build complete {
  "config": {
    "sphinx": {
      "buildDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/_build/html",
      "confDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source",
      "doctreeDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/_build/doctrees",
      "srcDir": "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source",
      "command": [
        "sphinx-build",
        "-M",
        "html",
        "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source",
        "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/_build/html",
        "-d",
        "/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/_build/doctrees"
      ],
      "version": "7.2.6"
    },
    "server": {
      "logLevel": "debug"
    }
  },
  "error": false,
  "warnings": 0
}
[esbonio.lsp] Getting initial doctree for: '/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/index.rst'
Cancel notification for unknown message id "2"
Cancel notification for unknown message id "1"
[esbonio.lsp] Getting initial doctree for: '/Users/will/Library/CloudStorage/Dropbox/research/macro/pyscope/docs/source/index.rst'
Cancel notification for unknown message id "5"
Cancel notification for unknown message id "7"
Cancel notification for unknown message id "8"
Cancel notification for unknown message id "9"
[client] HTML Path '/index.html'
[esbonio.lsp] esbonio.server.preview: {'show': False}
[esbonio.lsp] Starting preview server
[Error - 5:18:01 PM] Client Esbonio Language Server: connection to server is erroring. Shutting down server.
[Error - 5:18:01 PM] Client Esbonio Language Server: connection to server is erroring. Shutting down server.
[Error - 5:18:03 PM] Stopping server timed out
[Error - 5:18:03 PM] Stopping server failed
Error: Stopping the server timed out
    at /Users/will/.vscode/extensions/swyddfa.esbonio-0.11.0/dist/node/extension.js:1:102414
[Error - 5:18:03 PM] Stopping server failed
Error: Stopping the server timed out
    at /Users/will/.vscode/extensions/swyddfa.esbonio-0.11.0/dist/node/extension.js:1:102414
```

### (Optional) Settings from conf.py

_No response_

### PR DESCRIPTION
**Pull request by Nitorac**
Workaround to fix [Preview of rst files not working #790](https://github.com/swyddfa/esbonio/issues/790).

To limit any retrocompatibility issues, a Thread is used (instead of the current Process) only if we are on Linux.

### CODE REVIEW

**Comment by Nitorac** [comment]
(sorry for the force push, the commit had not the correct author)

**Comment by Nitorac** [comment]
Tested successfully on Ubuntu 24.04 with Python 3.12.3 (for the Thread part) and on Windows 11 with Python 3.12.6 (for the old Process part)

I'm open to any feedback

**Comment by alcarney** [comment]
Awesome, thanks for this!

I've only taken a quick glance, but it looks good to me so far. I'll try and have a proper look over the next week or so :)

**Comment by alcarney** [comment]
Ok, I've resurrected the ci pipelines for the `0.x` branch and have (hopefully! :crossed_fingers:) reconfigured things so that pushing a release from there works also.

However, having re-read #790 I noticed that the issue was originally reported on MacOS - could you tweak this PR so that a `Thread` is used for all platforms? (Apologies for not noticing sooner! :sweat_smile:)

While you're at it could you also add a changelog entry in a file `lib/esbonio/changes/790.fix.rst` (See [here](https://github.com/alcarney/esbonio/blob/1104ea5067d6b09f489d8652420cea351c9fec12/lib/esbonio/changes/621.misc.rst) for an example). Feel free to append `by @Nitorac` to your message so that you get the credit for the contribution on the GitHub release page :)

**Comment by Nitorac** [comment]
> Ok, I've resurrected the ci pipelines for the `0.x` branch and have (hopefully! 🤞) reconfigured things so that pushing a release from there works also.

Good news ! 

> However, having re-read #790 I noticed that the issue was originally reported on MacOS - could you tweak this PR so that a `Thread` is used for all platforms? (Apologies for not noticing sooner! 😅)

Oh yeah you're right, I didn't pay attention to that, it's hard to understand what environments are affected !
So I agree with you, I will edit the PR to remove the Process part entirely.

> While you're at it could you also add a changelog entry in a file `lib/esbonio/changes/790.fix.rst` (See [here](https://github.com/alcarney/esbonio/blob/1104ea5067d6b09f489d8652420cea351c9fec12/lib/esbonio/changes/621.misc.rst) for an example). Feel free to append `by @Nitorac` to your message so that you get the credit for the contribution on the GitHub release page :)

I will add it. Thanks for your explanations !

**Comment by Nitorac** [comment]
@alcarney The main part is done, but I have a question :
I couldn't understand why on non-Linux systems, a Queue was used to fetch the preview server port after creating it. (https://github.com/swyddfa/esbonio/blob/0ecf59f065d45d8fa8f1391e47d56916f7006419/lib/esbonio/esbonio/lsp/sphinx/__init__.py#L443)

Since I use a Thread now, I have just removed it, but I don't want to make any mistakes here !


Btw, as before, I tested and it worked on Ubuntu 24.04 with Python 3.12.3 and on Windows 11 with Python 3.12.6.

**Comment by alcarney** [comment]
> I couldn't understand why on non-Linux systems, a Queue was used to fetch the preview server port after creating it

I don't remember the exact details, but in order to share objects with a `multiprocessing.Process` they must be pickle-able. For some reason the server object was only pickle-able on Linux, so the Queue was used on other platforms as a work around.

Now that we're using a Thread that's no longer necessary :)

**Review by alcarney — APPROVED** [review]
Thanks again for working on this - looks good to me! :)

**Pull request merged**
