### PR TITLE
Links rework

### PR DESCRIPTION
**Pull request by goyalyashpal**
destinations:
* https://github.com/swyddfa/esbonio/blob/develop/lib/esbonio/README.md#installation
* https://github.com/swyddfa/esbonio/blob/develop/README.md

seeing the duplicacy in content of some of the readme files, i got a feeling they were autogenerated. is that the case?

### CODE REVIEW

**Comment by alcarney** [comment]
Thanks! 

> seeing the duplicacy in content of some of the readme files, i got a feeling they were autogenerated. is that the case?

No, just some of the content is copy-pasted around :sweat_smile:

**Comment by goyalyashpal** [comment]
ahwww, the pypi listing has not took picked up the previous readme changes. ohwkayh. got it.
i think it's similar to [f-droid repo] then, which picks changes upto the `HEAD` of the release `tag`

[commit history]: https://github.com/swyddfa/esbonio/commits/develop/lib/esbonio/README.md?since=2024-01-10&until=2024-03-06
[v0.16.4]: https://github.com/swyddfa/esbonio/releases/tag/esbonio-language-server-v0.16.4

* [pypi][esbonio] says: `Released: Jan 12, 2024`
* release latest tag: [v0.16.4]
* [commit history] says: `lsp: Update README` https://github.com/swyddfa/esbonio/commit/065542110838c2bae176a1d5c9a2040f4e48f056

[f-droid repo]: https://f-droid.org/

oh lol, gotta be careful next time 😆. retagging for non-code changes can be ohkay?? but i don't think bumping version just for readme would be good.

_moving my comment from https://github.com/swyddfa/awdur/issues/20 here:_

----

[swyddfa.esbonio]: https://open-vsx.org/vscode/item?itemName=swyddfa.esbonio "Esbonio vsc extension"
[github page]: https://swyddfa.github.io/esbonio/docs/latest/en/lsp/getting-started.html
[esbonio]: https://pypi.org/project/esbonio/

[vsc extension configuration page]: https://docs.esbon.io/en/latest/lsp/editors/vscode.html#configuration
[ls-readme-install]: https://github.com/swyddfa/esbonio/blob/bdd8e7c73699af15c7d560b6316eec3e4148431c/lib/esbonio/README.md?plain=1#L43



though 
* i cant get the restructured text preview, neither in browser, nor in in vscodium to work
* i installed esbonio like so: `pipx install esbonio --include-deps` (as per the changes in aforementioned commit)
* as there's no `bin` folder in pipx installs; i have set the esbonio-python-path for [swyddfa.esbonio] vsc-extension  like so:

```
	"esbonio.server.debugLaunch": true,
	"esbonio.server.pythonPath": "<some_dir>/pipx/venvs/esbonio/Scripts/python.exe",
```


* the extension shows following warnings and errors on running `esbonio: open preview to the side`, and no preview pane is shown even for plain standalone `.rst` files.
* the [vsc extension configuration page] doesnt seem to mention anything about `conf.py` issue. 

```
Unable to find your 'conf.py', features that depend on Sphinx will be unavailable
```

Abridged logs from output panel:

```log
[Error - <time>] Server initialization failed.
Error: command 'esbonio.server.build' already exists
...
[Error - <time>] Esbonio Language Server client: couldn't create connection to server.
Error: command 'esbonio.server.build' already exists
...
[client] Error: command 'esbonio.server.build' already exists
[Error - <time>] Sending document notification textDocument/didOpen failed
Error: command 'esbonio.server.build' already exists
...

```




### versions:

```console
$ esbonio --version
v0.16.4

$ codium --list-extensions --show-versions | grep esbonio
swyddfa.esbonio@0.11.0

$ codium --version
1.85.0
00c993f9b9a2a07730235274df02f05bd76575f7
x64

$ systeminfo | grep -iA1 "os name"
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.19045 N/A Build 19045

```

**Comment by alcarney** [comment]
You've found this repo in the middle of a big rewrite, so unfortunately the documentation isn't entirely consistent yet :/ 

Since you're using `v0.11.0` of the VSCode extension, then you will need to refer to [this version of the documentation](https://docs.esbon.io/en/esbonio-language-server-v0.16.4/lsp/getting-started.html?editor=vscode-esbonio).

To respond to some of your points... 
- Installing esbonio using `pipx` won't help you too much, the `0.16.x` version of the server needs to be installed into the same environment you use to build your documentation. And the upcoming `1.0` release will be distributed as part of the VSCode extension itself (pipx will be the recommended installation option for other editors).
- The `Unable to find your 'conf.py', features that depend on Sphinx will be unavailable` warning is expected if you're not using Sphinx. If you are using Sphinx however, then setting the `esbonio.sphinx.confDir` option to the folder that contains your `conf.py` should help.
- Currently, esbonio can only be used to preview Sphinx projects, not standalone rst files.

Alternatively... if you want to try the upcoming 1.0 release you would have to install the `0.92.x` pre-release version of the VSCode extension

Hope that clears up some of your issues at least!

**Comment by goyalyashpal** [comment]
> * Currently, esbonio can only be used to preview Sphinx projects, not standalone rst files.

ahkykayh. i dont know how i inferred or hoped that. prolly i was too used to working with extensions for asciidoc & markdown etc. thanks for sharing & clarifyong things up 😇

anyhow, several hours ago from the pipx install itself, i ran `sphinx-quickstart` which created this `Makefile` to perform `html` generation. i would see to hook it up via [`entr`][9KAp_zWeI34] or smth if available on windows to run automatically on file change & with some `html-server` to serve those files afresh to the browser.

[9KAp_zWeI34]: https://www.youtube.com/watch?v=9KAp_zWeI34 "Automating Everything in Linux with ENTR!"

**Comment by alcarney** [comment]
There's also [sphinx-autobuild](https://github.com/sphinx-doc/sphinx-autobuild) if you dont want to roll your own :)

**Pull request merged**
